[2024-05-21T15:07:55.300+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T15:07:55.313+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_task manual__2024-05-21T09:12:34.180878+00:00 [queued]>
[2024-05-21T15:07:55.316+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_task manual__2024-05-21T09:12:34.180878+00:00 [queued]>
[2024-05-21T15:07:55.316+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-21T15:07:55.412+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_task> on 2024-05-21 09:12:34.180878+00:00
[2024-05-21T15:07:55.416+0530] {standard_task_runner.py:63} INFO - Started process 74412 to run task
[2024-05-21T15:07:55.418+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'load_task', 'manual__2024-05-21T09:12:34.180878+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpgieqbp2z']
[2024-05-21T15:07:55.419+0530] {standard_task_runner.py:91} INFO - Job 41: Subtask load_task
[2024-05-21T15:07:55.517+0530] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.load_task manual__2024-05-21T09:12:34.180878+00:00 [running]> on host prince-5192
[2024-05-21T15:07:55.647+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='prince.yadav@tothenew.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T09:12:34.180878+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T09:12:34.180878+00:00'
[2024-05-21T15:07:55.648+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T15:07:55.659+0530] {logging_mixin.py:188} INFO - /////////////////// 	 Loading started 	///////////////////////////
[2024-05-21T15:07:55.659+0530] {logging_mixin.py:188} INFO - /////////////////// 	 Pulling data from xcomm 	///////////////////////////
[2024-05-21T15:07:55.665+0530] {logging_mixin.py:188} INFO - /////////////////// 	 Making connection to s3 	///////////////////////////
[2024-05-21T15:07:55.670+0530] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-05-21T15:07:55.670+0530] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-05-21T15:07:58.839+0530] {logging_mixin.py:188} INFO - /////////////////// 	 Data Saved to S3 Bucket	///////////////////////////
[2024-05-21T15:07:58.840+0530] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T15:07:58.841+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T15:07:58.845+0530] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_task, run_id=manual__2024-05-21T09:12:34.180878+00:00, execution_date=20240521T091234, start_date=20240521T093755, end_date=20240521T093758
[2024-05-21T15:07:59.001+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T15:07:59.012+0530] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-21T15:07:59.059+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
