[2024-05-21T14:34:37.027+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T14:34:37.039+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.extract_task scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-21T14:34:37.042+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.extract_task scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-21T14:34:37.042+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-21T14:34:37.108+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_task> on 2024-05-20 00:00:00+00:00
[2024-05-21T14:34:37.111+0530] {standard_task_runner.py:63} INFO - Started process 55192 to run task
[2024-05-21T14:34:37.112+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'extract_task', 'scheduled__2024-05-20T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp_lqjlwr_']
[2024-05-21T14:34:37.113+0530] {standard_task_runner.py:91} INFO - Job 28: Subtask extract_task
[2024-05-21T14:34:37.226+0530] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.extract_task scheduled__2024-05-20T00:00:00+00:00 [running]> on host prince-5192
[2024-05-21T14:34:37.365+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='prince.yadav@tothenew.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T00:00:00+00:00'
[2024-05-21T14:34:37.366+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T14:34:37.665+0530] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-05-21T14:34:37.665+0530] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-05-21T14:34:39.932+0530] {xcom.py:675} ERROR - Object of type bytes is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2024-05-21T14:34:39.933+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T14:34:39.933+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/prince/airflow-workspace/airflow/scripts/extract.py", line 11, in extract_from_s3
    kwargs['ti'].xcom_push(key='raw_data', value=data)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2024-05-21T14:34:40.108+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=extract_task, run_id=scheduled__2024-05-20T00:00:00+00:00, execution_date=20240520T000000, start_date=20240521T090437, end_date=20240521T090440
[2024-05-21T14:34:40.177+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task extract_task (Object of type bytes is not JSON serializable; 55192)
[2024-05-21T14:34:40.213+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T14:34:40.225+0530] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T14:34:40.225+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
